//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlumnoxClase
    {
        public int idAlumnoxClase { get; set; }
        public Nullable<int> idAlumno { get; set; }
        public Nullable<int> idProfesorxClase { get; set; }
        public Nullable<System.DateTime> fechaDesde { get; set; }
        public Nullable<System.DateTime> fechaHasta { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual ProfesorxClase ProfesorxClase { get; set; }
    }
}
