//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class EjercicioxPlan
    {
        public int idEjercicioxPlan { get; set; }
        public int idEjercicio { get; set; }
        public int idPlan { get; set; }
        public Nullable<int> repeticiones { get; set; }
        public Nullable<int> series { get; set; }
        public string observaciones { get; set; }
        public string dia { get; set; }
    
        public virtual Ejercicio Ejercicio { get; set; }
        public virtual Planes Planes { get; set; }
    }
}
