//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDGimnasioEntities : DbContext
    {
        public BDGimnasioEntities()
            : base("name=BDGimnasioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alumno> Alumno { get; set; }
        public virtual DbSet<AlumnoxClase> AlumnoxClase { get; set; }
        public virtual DbSet<Asistencia> Asistencia { get; set; }
        public virtual DbSet<Ciudad> Ciudad { get; set; }
        public virtual DbSet<Clase> Clase { get; set; }
        public virtual DbSet<Ejercicio> Ejercicio { get; set; }
        public virtual DbSet<EjercicioPlanAlumno> EjercicioPlanAlumno { get; set; }
        public virtual DbSet<EjercicioxPlan> EjercicioxPlan { get; set; }
        public virtual DbSet<Maquina> Maquina { get; set; }
        public virtual DbSet<Planes> Planes { get; set; }
        public virtual DbSet<PlanxAlumno> PlanxAlumno { get; set; }
        public virtual DbSet<Profesor> Profesor { get; set; }
        public virtual DbSet<ProfesorxClase> ProfesorxClase { get; set; }
        public virtual DbSet<Provincia> Provincia { get; set; }
        public virtual DbSet<TipoEjercicio> TipoEjercicio { get; set; }
        public virtual DbSet<TipoPlan> TipoPlan { get; set; }
        public virtual DbSet<Titulo> Titulo { get; set; }
        public virtual DbSet<TituloxProfesor> TituloxProfesor { get; set; }
        public virtual DbSet<vPlanPersonalizado> vPlanPersonalizado { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
