//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TituloxProfesor
    {
        public int idTituloxProfesor { get; set; }
        public Nullable<int> idTitulo { get; set; }
        public Nullable<int> idProfesor { get; set; }
        public Nullable<System.DateTime> fechaEgreso { get; set; }
    
        public virtual Profesor Profesor { get; set; }
        public virtual Titulo Titulo { get; set; }
    }
}
