//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class vPlanPersonalizado
    {
        public string Ejercicio { get; set; }
        public Nullable<int> Series { get; set; }
        public Nullable<int> Repeticiones { get; set; }
        public string Maquina { get; set; }
        public string Dia { get; set; }
        public string Observaciones { get; set; }
        public string PlanBase { get; set; }
        public Nullable<int> idAlumno { get; set; }
        public Nullable<int> idPxA { get; set; }
        public Nullable<System.DateTime> fechaDesde { get; set; }
        public string Alumno { get; set; }
        public string DNI { get; set; }
        public string Direccion { get; set; }
        public string Email { get; set; }
        public string Telefono { get; set; }
    }
}
